#include "interface.h"	// TRAIN_SENDCOMMAND, TRAIN_DATA

#include "route.h"

TRAIN_SENDCOMMAND(Route_SendCommand, TRAIN_ROUTE_MAXADDRESS, TRAIN_ROUTE_MAXCOMMAND, 0xD000 /*11010000 00000000*/)

#define TRAIN_ROUTE_DATA(NAME, COMMAND) TRAIN_DATA(NAME, COMMAND, Route_SendCommand, TRAIN_ROUTE_MAXADDRESS)

TRAIN_ROUTE_DATA(Route_Throw, 31 /*0011111*/)
TRAIN_ROUTE_DATA(Route_Clear, 44 /*0101100*/)
