#include "interface.h"	// __TRAIN_SENDCOMMAND, __TRAIN_DATA, __TRAIN_UDATA
#include "route.h"

#include "switch.h"

__TRAIN_SENDCOMMAND(Switch_SendCommand, TRAIN_SWITCH_MAXADDRESS, TRAIN_SWITCH_MAXCOMMAND, 0x4000 /*01000000 00000000*/)

#define __TRAIN_SWITCH_DATA(NAME, COMMAND) __TRAIN_DATA(NAME, COMMAND, Switch_SendCommand, TRAIN_SWITCH_MAXADDRESS)
#define __TRAIN_SWITCH_UDATA(NAME, COMMAND, MAX) __TRAIN_UDATA(NAME, COMMAND, MAX, Switch_SendCommand, TRAIN_SWITCH_MAXADDRESS)

__TRAIN_SWITCH_DATA(Switch_ThrowThrough, 0 /*0000000*/)
__TRAIN_SWITCH_DATA(Switch_ThrowOut, 31 /*0011111*/)
__TRAIN_SWITCH_DATA(Switch_SetAddress, 43 /*0101011*/)
__TRAIN_SWITCH_UDATA(Switch_AssignToRouteThrough, 64 /*1000000*/, TRAIN_ROUTE_MAXADDRESS)
__TRAIN_SWITCH_UDATA(Switch_AssignToRouteOut, 96 /*1100000*/, TRAIN_ROUTE_MAXADDRESS)
