#include "interface.h"	// TRAIN_SENDCOMMAND, TRAIN_DATA, TRAIN_UDATA
#include "route.h"

#include "switch.h"

TRAIN_SENDCOMMAND(Switch_SendCommand, TRAIN_SWITCH_MAXADDRESS, TRAIN_SWITCH_MAXCOMMAND, 0x4000 /*01000000 00000000*/)

#define TRAIN_SWITCH_DATA(NAME, COMMAND) TRAIN_DATA(NAME, COMMAND, Switch_SendCommand, TRAIN_SWITCH_MAXADDRESS)
#define TRAIN_SWITCH_UDATA(NAME, COMMAND, MAX) TRAIN_UDATA(NAME, COMMAND, MAX, Switch_SendCommand, TRAIN_SWITCH_MAXADDRESS)

TRAIN_SWITCH_DATA(Switch_ThrowThrough, 0 /*0000000*/)
TRAIN_SWITCH_DATA(Switch_ThrowOut, 31 /*0011111*/)
TRAIN_SWITCH_DATA(Switch_SetAddress, 43 /*0101011*/)
TRAIN_SWITCH_UDATA(Switch_AssignToRouteThrough, 64 /*1000000*/, TRAIN_ROUTE_MAXADDRESS)
TRAIN_SWITCH_UDATA(Switch_AssignToRouteOut, 96 /*1100000*/, TRAIN_ROUTE_MAXADDRESS)
